import type { MeetingAnalysis } from "@/types/analysis"
import jsPDF from "jspdf"

export function toMarkdown(analysis: MeetingAnalysis): string {
  const { title, summary, actionItems, decisions, participants } = analysis

  const items = actionItems
    .map((a) => `- [ ] **${a.task}** — ${a.assignee} | Due: ${a.due} | Priority: ${a.priority}`)
    .join("\n")

  const dec = decisions.map((d) => `- ${d}`).join("\n")
  const people = participants.map((p) => `- ${p.name} (${p.role})`).join("\n")

  return `# ${title}

## Summary
${summary}

## Action Items
${items || "None"}

## Key Decisions
${dec || "None"}

## Participants
${people || "None"}

---
*Generated by Minutely*
`
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text)
}

export function downloadMarkdown(analysis: MeetingAnalysis): void {
  const md = toMarkdown(analysis)
  const blob = new Blob([md], { type: "text/markdown" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${analysis.title.replace(/\s+/g, "-").toLowerCase()}.md`
  a.click()
  URL.revokeObjectURL(url)
}

export function downloadPDF(analysis: MeetingAnalysis): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let y = 20

  const addText = (
    text: string,
    size: number,
    style: "normal" | "bold" = "normal",
    color: [number, number, number] = [30, 30, 30]
  ) => {
    doc.setFontSize(size)
    doc.setFont("helvetica", style)
    doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, maxWidth)
    if (y + lines.length * (size * 0.4) > 280) {
      doc.addPage()
      y = 20
    }
    doc.text(lines, margin, y)
    y += lines.length * (size * 0.4) + 2
  }

  const addSection = (title: string) => {
    y += 4
    doc.setDrawColor(220, 220, 220)
    doc.line(margin, y, pageWidth - margin, y)
    y += 6
    addText(title, 11, "bold", [80, 80, 80])
    y += 1
  }

  // Title
  addText(analysis.title, 18, "bold", [10, 10, 10])
  y += 2
  addText(`Generated by Minutely · ${new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric"
  })}`, 9, "normal", [150, 150, 150])
  y += 4

  // Summary
  addSection("SUMMARY")
  addText(analysis.summary, 10)

  // Action Items
  addSection(`ACTION ITEMS (${analysis.actionItems.length})`)
  if (analysis.actionItems.length === 0) {
    addText("None", 10, "normal", [150, 150, 150])
  } else {
    analysis.actionItems.forEach((item, i) => {
      addText(`${i + 1}. ${item.task}`, 10, "bold")
      addText(`   ${item.assignee} · Due: ${item.due} · ${item.priority} priority`, 9, "normal", [100, 100, 100])
      y += 1
    })
  }

  // Decisions
  addSection("KEY DECISIONS")
  if (analysis.decisions.length === 0) {
    addText("None", 10, "normal", [150, 150, 150])
  } else {
    analysis.decisions.forEach((d) => {
      addText(`• ${d}`, 10)
    })
  }

  // Participants
  addSection("PARTICIPANTS")
  if (analysis.participants.length === 0) {
    addText("None", 10, "normal", [150, 150, 150])
  } else {
    analysis.participants.forEach((p) => {
      addText(`${p.name} — ${p.role}`, 10)
    })
  }

  doc.save(`${analysis.title.replace(/\s+/g, "-").toLowerCase()}.pdf`)
}

export function toNotionClipboard(analysis: MeetingAnalysis): string {
  return toMarkdown(analysis)
}